version: 2
jobs:
  build:
    working_directory: ~/icon-navigation
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: yarn 
      - run:
          command: |
            yarn run test